### ISSUE TITLE
Hello, I want to reproduce your code. Can you provide more details in the data preparation section？

### ISSUE THREAD

**Issue by YTUW** [katerynaCh/multimodal-emotion-recognition#1]

**Comment by katerynaCh** [comment]
Hi! For data preparation, you need to download the [RAVDESS](https://zenodo.org/record/1188976#.YlkZYyjP1PZ) dataset and follow the steps described in readme: organize the data in the folder; install facenet; and run preprocessing scripts in ravdess_preprocessing. Overall, this extracts faces from video, and aligns audio and video to 3.6 seconds, as well as samples 15 frames from video. If you have any specific question/issue at any step, feel free to ask

**Comment by katerynaCh** [comment]
I'm closing this for now, feel free to reopen if you face any issues
