### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by Lylb** [katerynaCh/multimodal-emotion-recognition#10]
In accordance with the code of the paper ,I reproduced the experimental results to achieve 92 accuracy.

**Comment by katerynaCh** [comment]
Could you share what split you are using? Since there is not fixed train-val-test split for RAVDESS, the results could be very different between splits

**Comment by Lylb** [comment]
my split test:1、2、5、6、9 ,val:10、3、7、4.For some reason my test are always 5 according tothe code

**Comment by katerynaCh** [comment]
indeed you are right, I have fixed the create_annotations.py so you can pull the newest version and it should now split into 4 - 4 - 16 identities for test-val-train (I used a different codebase for data preprocessing in the paper, so it was correct there). 

But in general, RAVDESS dataset is very small and performance between different splits can vary quite significantly, so it is natural to obtain better or worse results than in the literature depending on the split. So if you want to compare your method with some baseline, you need to make sure to evaluate it on the same split. 
I will try to add in the future what splits exactly were used in my paper.

**Comment by Lylb** [comment]
Thnak you for your guidance,but I found that following the modified code to reproduce my split test1、2、3,val4、5、6、7

**Comment by katerynaCh** [comment]
@Lylb I have just double checked and it works fine for me, i.e., 4 ids for test, 4 ids for val, and 16 for train. can you double check that you have all 24 actors downloaded?

**Comment by stonewalking** [comment]
Hello author,
could you provide the best 5 fold splits from the paper?
