### ISSUE TITLE
Thank you for your work

### ISSUE THREAD

**Issue by She-yh** [katerynaCh/multimodal-emotion-recognition#4]
Hello, Dear Author

I reorganized your code to fit my needs, and open sourced the code, you can click [here](https://github.com/She-yh/End-to-End-Multimodal-emotion-recognition) to visit it. To thank your work, I mentioned you in the README.md. This is my first time to do such a thing and I don't know if that's okay, so I'd like to get your permission.

Looking forward to hearing from you
Best regards.

**Comment by katerynaCh** [comment]
Thank you!
