### ISSUE TITLE
There were some problems during training

### ISSUE THREAD

**Issue by Pike12** [katerynaCh/multimodal-emotion-recognition#5]
Why does top1 have very low accuracy ？
![image](https://user-images.githubusercontent.com/88581919/230337800-3793ac85-4e95-43bb-a2cf-7698a10e499f.png)

**Comment by katerynaCh** [comment]
can you provide more details on which model are you using, how you are training, are you using ravdess dataset?

**Comment by Pike12** [comment]
Yes, because ravdess dataset is too large, I choose to use the voice and video data of the first four personnel for training, and the training steps are also operated according to your instructions.

![image](https://user-images.githubusercontent.com/88581919/230353223-12ad1080-5172-4bb0-8dae-11510bf140d0.png)

**Comment by katerynaCh** [comment]
Although I was not able to test with a smaller dataset to verify, I believe that this is the cause of the issue: RAVDESS is already pretty small by itself, selecting only four actors is likely not enough to learn something meaningful. If you are facing out of memory issues, you might try reducing the batch size
