### ISSUE TITLE
predicted class

### ISSUE THREAD

**Issue by ChethanN01** [katerynaCh/multimodal-emotion-recognition#8]
how do i know the predicted class?
i am getting the precision but i couldn't able to interpret the predicted class from pretrained weights..

**Comment by katerynaCh** [comment]
Hi, you can check the output layer for which class produces highest probability and then the order of the classes is the following: 01 = neutral, 02 = calm, 03 = happy, 04 = sad, 05 = angry, 06 = fearful, 07 = disgust, 08 = surprised
